services:
  postgres:
    container_name: dach-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: dachpc_database
      POSTGRES_USER: dachdach
      POSTGRES_PASSWORD: dachdach
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - dachpcnetwork
    restart: unless-stopped

networks:
  dachpcnetwork:
    driver: bridge

volumes:
  postgres: